"""added lms dashboard and streaks

Revision ID: 6577620065af
Revises: 
Create Date: 2026-05-17 20:04:27.679896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6577620065af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('xp_val', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_title'), 'courses', ['title'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_badges_id'), 'user_badges', ['id'], unique=False)
    op.add_column('user_progress', sa.Column('progress_percent', sa.Float(), nullable=True))
    op.add_column('user_progress', sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('user_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_progress', 'course_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True,
               postgresql_using='course_id::integer')
    op.drop_constraint(op.f('user_progress_user_id_fkey'), 'user_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_progress', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_progress', 'courses', ['course_id'], ['id'])
    op.drop_column('user_progress', 'streak_count')
    op.drop_column('user_progress', 'completed_days')
    op.drop_column('user_progress', 'unlocked_level')
    op.drop_column('user_progress', 'last_active_date')
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_date')
    op.drop_column('users', 'current_streak')
    op.add_column('user_progress', sa.Column('last_active_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user_progress', sa.Column('unlocked_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_progress', sa.Column('completed_days', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user_progress', sa.Column('streak_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.create_foreign_key(op.f('user_progress_user_id_fkey'), 'user_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_progress', 'course_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_progress', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_progress', 'last_updated')
    op.drop_column('user_progress', 'progress_percent')
    op.drop_index(op.f('ix_user_badges_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_courses_title'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
